# Generated by Django 5.0.2 on 2025-03-19 05:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the quiz category', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='A detailed description of the category')),
                ('icon', models.CharField(blank=True, help_text="CSS class for the category icon (e.g., 'fa-science')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the category was created')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The question text')),
                ('explanation', models.TextField(blank=True, help_text='Explanation of the correct answer (shown after answering)')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='The difficulty level of this question', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the question was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the question was last updated')),
                ('category', models.ForeignKey(help_text='The category this question belongs to', on_delete=django.db.models.deletion.CASCADE, to='quiz_app.category')),
            ],
            options={
                'ordering': ['category', 'difficulty', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='The text of this answer choice', max_length=255)),
                ('is_correct', models.BooleanField(default=False, help_text='Whether this choice is the correct answer')),
                ('question', models.ForeignKey(help_text='The question this choice belongs to', on_delete=django.db.models.deletion.CASCADE, to='quiz_app.question')),
            ],
            options={
                'ordering': ['question', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the quiz attempt was started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the quiz attempt was completed', null=True)),
                ('score', models.IntegerField(default=0, help_text='The total score achieved')),
                ('total_questions', models.IntegerField(default=0, help_text='The total number of questions in the quiz')),
                ('category', models.ForeignKey(help_text='The category of questions in this quiz', on_delete=django.db.models.deletion.CASCADE, to='quiz_app.category')),
                ('user', models.ForeignKey(blank=True, help_text='The user who took the quiz (null for anonymous users)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, help_text='Whether this response was correct')),
                ('response_time', models.DateTimeField(auto_now_add=True, help_text='When this question was answered')),
                ('question', models.ForeignKey(help_text='The question that was answered', on_delete=django.db.models.deletion.CASCADE, to='quiz_app.question')),
                ('quiz_attempt', models.ForeignKey(help_text='The quiz attempt this response belongs to', on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quizattempt')),
                ('selected_choice', models.ForeignKey(help_text='The choice that was selected', on_delete=django.db.models.deletion.CASCADE, to='quiz_app.choice')),
            ],
            options={
                'ordering': ['quiz_attempt', 'response_time'],
                'unique_together': {('quiz_attempt', 'question')},
            },
        ),
    ]
