# Generated by Django 5.0.2 on 2025-03-21 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Short biography or description')),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='avatars/')),
                ('date_of_birth', models.DateField(blank=True, help_text="User's date of birth", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the profile was last updated')),
                ('favorite_category', models.ForeignKey(blank=True, help_text="User's favorite quiz category", null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_app.category')),
                ('user', models.OneToOneField(help_text='The user this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
