# Generated by Django 4.2.20 on 2025-04-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='time_limit',
            field=models.IntegerField(default=0, help_text='Time limit for the quiz in seconds (0 means no limit)'),
        ),
    ]
